stages:
  train-modelnet40:
    cmd: python ./train.py -cd ./configs hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/train.yaml
      - ./configs/scheduler/multistep.yaml
      - ./configs/preprocess/preprocess_base.yaml
      - ./configs/optimizer/adam.yaml
      - ./configs/model/cls_model.yaml
      - ./configs/data/modelnet40.yaml
      - ./data/modelnet.py
      - ./data/io_utils.py
      - ./data_configs
      - ./datasets/modelnet40
      - ./model/cls_network.py
      - ./transforms/transformations.py
      - ./point_transformer
      - ./train.py
    outs:
      - ./exp/modelnet
  prepare-modelnet40:
    cmd: python ./prepare_data.py -cd ./configs -cn prepare_modelnet40 hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/prepare_modelnet40.yaml
      - ./datasets/modelnet40_raw/ModelNet40.zip
      - ./prepare_data.py
      - ./data/modelnet.py
      - ./data/io_utils.py
    outs:
      - ./datasets/modelnet40
  prepare-simple-shapes:
    cmd: python ./prepare_data.py -cd ./configs -cn prepare_simple_shapes hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/prepare_simple_shapes.yaml
      - ./datasets/shapes/dataset-v2.zip
      - ./prepare_data.py
      - ./data/simple_shapes.py
      - ./data/io_utils.py
    outs:
      - ./datasets/simple_shapes
