stages:
  train-modelnet40:
    cmd: python ./train.py -cd ./configs hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/train.yaml
      - ./configs/scheduler/multistep.yaml
      - ./configs/preprocess/preprocess_base.yaml
      - ./configs/optimizer/adam.yaml
      - ./configs/model/cls_model.yaml
      - ./configs/data/modelnet40.yaml
      - ./data/modelnet.py
      - ./data/io_utils.py
      - ./data_configs
      - ./datasets/modelnet40
      - ./model/cls_network.py
      - ./transforms/transformations.py
      - ./point_transformer
      - ./train.py
    outs:
      - ./exp/modelnet40
  train-modelnet10:
    cmd: python ./train.py -cd ./configs -cn train_modelnet10 hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/train_modelnet10.yaml
      - ./configs/scheduler/multistep.yaml
      - ./configs/preprocess/preprocess_base.yaml
      - ./configs/optimizer/adam.yaml
      - ./configs/model/cls_model.yaml
      - ./configs/datasets/modelnet10.yaml
      - ./data/modelnet.py
      - ./data/io_utils.py
      - ./data_configs
      - ./datasets/modelnet10
      - ./model/cls_network.py
      - ./transforms/transformations.py
      - ./point_transformer
      - ./train.py
    outs:
      - ./exp/modelnet10
  train-simple-shapes:
    cmd: python ./train.py -cd ./configs -cn ./train_simple_shapes hydra.output_subdir=null hydra.run.dir=. model.num_transformer_blocks=1
    deps:
      - ./configs/train_simple_shapes.yaml
      - ./configs/scheduler/multistep.yaml
      - ./configs/preprocess/preprocess_base.yaml
      - ./configs/optimizer/adam.yaml
      - ./configs/model/cls_model.yaml
      - ./configs/datasets/simple_shapes.yaml
      - ./data/simple_shapes.py
      - ./data/io_utils.py
      - ./data_configs/train_config.py
      - ./data_configs/preprocess_config.py
      - ./datasets/simple_shapes
      - ./model/cls_network.py
      - ./transforms/transformations.py
      - ./point_transformer
      - ./train.py
    outs:
      - ./exp/simple_shapes
  prepare-modelnet40:
    cmd: python ./prepare_data.py -cd ./configs/prepare -cn prepare_modelnet40 hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/prepare/prepare_modelnet40.yaml
      - ./datasets/modelnet40_raw/ModelNet40.zip
      - ./prepare_data.py
      - ./data/modelnet.py
      - ./data/io_utils.py
    outs:
      - ./datasets/modelnet40
  prepare-modelnet10:
    cmd: python ./prepare_data.py -cd ./configs/prepare -cn prepare_modelnet10 hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/prepare/prepare_modelnet10.yaml
      - ./datasets/modelnet10_raw/ModelNet10.zip
      - ./prepare_data.py
      - ./data/modelnet.py
      - ./data/io_utils.py
    outs:
      - ./datasets/modelnet10
  prepare-simple-shapes:
    cmd: python ./prepare_data.py -cd ./configs/prepare -cn prepare_simple_shapes hydra.output_subdir=null hydra.run.dir=.
    deps:
      - ./configs/prepare/prepare_simple_shapes.yaml
      - ./datasets/shapes/dataset-v2.zip
      - ./prepare_data.py
      - ./data/simple_shapes.py
      - ./data/io_utils.py
    outs:
      - ./datasets/simple_shapes
