channels:
  - defaults
  - conda-forge
  - pytorch-lts
  - rusty1s
dependencies:
  - python=3.8
  - pip
  - pytorch=1.8
  - cudatoolkit=10.2
  - ipykernel
  - pylint
  - autopep8
  - pytest=6.2
  - pip:
      - -f https://pytorch-geometric.com/whl/torch-1.8.0+cu102.html
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - torch-geometric~=1.7
