version: 1
formatters:
  default_console_thread:
    (): log_set.utc_formatter.ColoredUTCFormatter
    format: "%(log_color)s %(asctime)s %(levelname)s %(threadName)s %(module)s %(funcName)s %(message)s"
  default_console_process:
    (): log_set.utc_formatter.ColoredUTCFormatter
    format: "%(log_color)s %(asctime)s %(levelname)s %(processName)s %(module)s %(funcName)s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default_console_thread
    stream: ext://sys.stdout
loggers:
  pt.data:
    level: DEBUG
    handlers: [console]
    propagate: no
  pt.datasets:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
