vars:
  - ../../configs/datasets/modelnet40.yaml:path_to_zip,data_root
  - config_name: train_modelnet40
  - ../../configs/train_modelnet40.yaml:base_exp_dir,exp_dir

stages:
  download-dataset:
    wdir: ../..
    cmd: dw http://modelnet.cs.princeton.edu/ModelNet40.zip ${path_to_zip}
    outs:
      - ${path_to_zip}:
          persist: true

  prepare-dataset:
    wdir: ../..
    cmd: python ./prepare_data.py -cn train_modelnet40
    deps:
      - ./configs/datasets/modelnet40.yaml
      - ${path_to_zip}
      - ./configs/prepare_dataset.yaml
      - ./configs/transforms/simple_shapes
      - ./prepare_data.py
      - ./training/data/modelnet
    outs:
      - ${data_root}:
          cache: false

  prepare-config:
    wdir: ../..
    cmd: python ./resolve_config.py -cn ${config_name} model.num_transformer_blocks=5
    deps:
      - ./resolve_config.py
      - ./configs/${config_name}.yaml
    outs:
      - ${base_exp_dir}/config.yaml

  train:
    wdir: ../..
    cmd: python ./train.py -cn ${config_name}
    params:
      - ${base_exp_dir}/config.yaml:
        - params
        - optimizer
        - scheduler
        - model
        - train_transform
        - test_transform
    deps:
      - ./train.py
      - ./point_transformer
      - ./training/metrics
      - ./training/trainers
      - ${data_root}
      - ${base_exp_dir}/config.yaml
    outs:
      - ${base_exp_dir}/${exp_dir}:
          cache: false

