vars:
  - ../../configs/datasets/modelnet40.yaml:file_loc,data_root
  - config_name: train_modelnet40
  - ../../configs/train_modelnet40.yaml:base_exp_dir,exp_dir

stages:
  download-dataset:
    wdir: ../..
    cmd: python ./downloader.py --url http://modelnet.cs.princeton.edu/ModelNet40.zip --out ${file_loc}
    deps:
      - ./downloader.py
    outs:
      - ${file_loc}:
          persist: true

  prepare-dataset:
    wdir: ../..
    cmd: python ./prepare_data.py -cn ${config_name}
    deps:
      - ./configs/datasets/modelnet40.yaml
      - ${file_loc}
      - ./configs/prepare_dataset.yaml
      - ./configs/${config_name}.yaml
      - ./configs/transforms/simple_shapes
      - ./configs/transforms/modelnet
      - ./prepare_data.py
      - ./training/data/modelnet
    outs:
      - ${data_root}:
          cache: false

  prepare-config:
    wdir: ../..
    cmd: python ./resolve_config.py -cn ${config_name}
    deps:
      - ./resolve_config.py
      - ./configs/${config_name}.yaml
      - ./configs/datasets/modelnet40.yaml
      - ./configs/model/cls_model.yaml
      - ./configs/optimizer/sgd.yaml
      - ./configs/optimizer/adam.yaml
      - ./configs/scheduler/multistep.yaml
      - ./configs/transforms/modelnet
    outs:
      - ${base_exp_dir}/config.yaml

  train:
    wdir: ../..
    cmd: python ./train.py -cn config -cp ${base_exp_dir}
    params:
      - ${base_exp_dir}/config.yaml:
        - params
        - optimizer
        - scheduler
        - model
        - train_transform
        - test_transform
    deps:
      - ./train.py
      - ./point_transformer
      - ./training/metrics
      - ./training/trainers
      - ${data_root}
      - ${base_exp_dir}/config.yaml
    outs:
      - ${base_exp_dir}/${exp_dir}:
          cache: false

