defaults:
  - datasets: modelnet40
  - optimizer: sgd
  - model: cls_model
  - scheduler: multistep
  - preprocess: preprocess_base
  - prepare: prepare_modelnet40

train_load_workers: 2
test_load_workers: 2
test_batch_size: 512
train_batch_size: 256
max_epochs: 200
log_dir: ./exp/modelnet40
seed: 200
