defaults:
  - data: simple_shapes
  - optimizer: adam
  - model: cls_model

train_load_workers: 2
test_load_workers: 2
test_batch_size: 1024
train_batch_size: 256
max_epochs: 60
log_dir: ./exp
seed: 156
