vars:
  - ../../configs/datasets/simple_shapes.yaml:path_to_zip,data_root
  - ../../configs/train_simple_shapes.yaml:base_exp_dir,exp_dir
  - config_name: train_simple_shapes

stages:
  download:
    wdir: ../..
    cmd: gdown https://drive.google.com/uc?id=1xM5diKjMbp_PfNu--JG2A-ZeFk9TLkks -O ${path_to_zip}
    outs:
      - ${path_to_zip}

  prepare-dataset:
    wdir: ../..
    cmd: python ./prepare_data.py -cn ${config_name}
    deps:
      - ./configs/datasets/simple_shapes.yaml
      - ${path_to_zip}
      - ./configs/prepare_dataset.yaml
      - ./configs/transforms/simple_shapes
      - ./prepare_data.py
      - ./training/data/simple_shapes.py
    outs:
      - ${data_root}

  prepare-config:
    wdir: ../..
    cmd: python ./resolve_config.py -cn ${config_name}
    deps:
      - ./resolve_config.py
      - ./configs/${config_name}.yaml
    outs:
      - ${base_exp_dir}/config.yaml

  train:
    wdir: ../..
    cmd: python ./train.py -cn ${config_name}
    params:
      - ${base_exp_dir}/config.yaml:
        - params
        - optimizer
        - scheduler
        - model
        - train_transform
        - test_transform
    deps:
      - ./train.py
      - ./point_transformer
      - ./training/metrics
      - ./training/trainers
      - ${data_root}
      - ${base_exp_dir}/config.yaml
    outs:
      - ${base_exp_dir}/${exp_dir}:
          cache: false

