_target_: training.data.modelnet.modelnet.ModelNetDataset
data_root: ./datasets/modelnet40
file_loc: ./datasets/raw/modelnet40.zip
protocol: zip://
dataset_type: 40
train_load_sett: 
  _target_: training.data.dataloader_settings.LoadSettings
  num_workers: 2
  batch_size: 64
  pre_transform: null
  pre_filter: null
  transform: null
test_load_sett:
  _target_: training.data.dataloader_settings.LoadSettings
  num_workers: 2
  batch_size: 128
  pre_transform: null
  pre_filter: null
  transform: null
